stages:
  - build
  - test
  - deploy

before_script:
  - echo "Starting CI/CD Pipeline..."

# build
build-client:
  stage: build
  image: oven/bun:latest
  script:
    - cd ./client
    - bun i
    - bun run build
  artifacts:
    paths:
      - ./client/dist/

build-server:
  stage: build
  image: golang:alpine
  script:
    - cd ./server
    - go mod download
    - go build .

# test
test-client:
  stage: test
  image: oven/bun:latest
  script:
    - cd ./client
    - bun test

test-server:
  stage: test
  image: golang:alpine
  script:
    - cd ./server
    - go mod download
    - go test

# deploy
deploy-client:
  stage: deploy
  environment: production
  script:
    - echo "Deploying client..."
    - echo "Client successfully deployed."

deploy-server:
  stage: deploy
  environment: production
  script:
    - echo "Deploying server..."
    - echo "Server sucessfully deployed."
