services:
  database:
    image: mysql:latest
    restart: always
    env_file:
      - "./db.env"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: "exit 0"
  server:
    build:
      context: ./server
    depends_on:
      database:
        condition: service_healthy
    container_name: fyp-server
    hostname: fyp-server
    env_file:
      - "./server/.env"
    ports:
      - "1323:1323"
  client:
    build:
      context: ./client
    container_name: fyp-client
    hostname: fyp-client
    ports:
      - "5173:5173"
volumes:
  my-db: